server:
  port: 8126
  servlet:
    context-path: /demo

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root123
        slave:
          url: jdbc:mysql://127.0.0.1:3306/testdb1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root123
      mp-enabled: true

logging:
  level:
    com.yuansb.demo.multi.datasource.mybatis: debug